### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by SDR92** [adimalla/Minimal-TCP-IP-Stack#10]
In the file main.c the following reference is quite ambiguous:

 * Please Take prior permission from Dr. Jason Losh and Respective Owners of the,
 * API Libraries if you are a student at The University of Texas at Arlington and,
 * wish to use part of the code in your project.

Above this reference you also say that the license is MIT. So is this file to be used by everyone under MIT License or the usage it's conditioned to the reply Dr. Jason Losh would provide?

**Comment by adimalla** [comment]
If you are student at UTA and in one of Dr Losh's course, its advised you
shouldn't use this code without his permission.

Otherwise you can, hence the MIT license.

Best,
Aditya

**Comment by adimalla** [comment]
Resolved
